routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@root')->name('root');

Route::get('/reprinted', function () {
    return view('reprinted');
});

Route::get('/sites','LinkController@index')->name('links.index');
Route::get('/links/create','LinkController@create')->name('links.create');
Route::post('/links/store','LinkController@store')->name('links.store');

Route::get('users_json','UsersController@usersJson')->name('users.json');


Auth::routes();

Route::group(['middleware' => 'auth'], function() {
    Route::get('/email_verify_notice', 'HomeController@emailVerifyNotice')
        ->name('email_verify_notice');

    Route::get('/email_verification/send', 'EmailVerificationController@send')->name('email_verification.send');
    Route::get('/email_verification/verify', 'EmailVerificationController@verify')->name('email_verification.verify');
    Route::get('/about','HomeController@about')->name('about');

    Route::resource('notifications', 'NotificationsController', ['only' => ['index']]);

    Route::group(['middleware' => 'email_verified'], function() {
        Route::resource('users','UsersController');
        Route::any('users/upload','UsersController@upload')->name('users.upload');

        Route::resource('posts','PostsController',['only' => ['index', 'create', 'store', 'update', 'edit', 'destroy']]);
        Route::post('upload_image', 'PostsController@uploadImage')->name('posts.upload_image');
        Route::resource('replies', 'RepliesController', ['only' => ['store', 'destroy']]);
        Route::get('users/{user}/follow', 'UsersController@follow')->name('users.follow');
        Route::get('users/{user}/unfollow', 'UsersController@unfollow')->name('users.unfollow');

        Route::post('tweets','TweetsController@store')->name('tweets.store');

    });

});
Route::resource('tweets','TweetsController',['only' => ['index','show']]);

Route::get('posts/{post}/{slug?}', 'PostsController@show')->name('posts.show');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/oauth/github', 'AuthController@redirectToProvider')->name('oauth.github');
Route::get('/oauth/github/callback', 'AuthController@handleProviderCallback')->name('oauth.github.callback');

Route::get('/oauth/qq', 'AuthController@qqRedirectToProvider')->name('oauth.qq');
Route::get('/oauth/qq/callback', 'AuthController@qqHandleProviderCallback')->name('oauth.qq.callback');

Route::get('oauth/perfect', 'AuthController@perfect')->name('oauth.perfect');
Route::post('oauth/perfect/store','AuthController@store')->name('auth.perfect.store');



//后台相关
Route::get('/admin/login','Admin\Auth\LoginController@showLoginForm');
Route::post('/admin/login','Admin\Auth\LoginController@login')->name('admin.login');
Route::post('/admin/logout','Admin\Auth\LoginController@logout')->name('admin.logout');

Route::get('/admin/index',function (){
    return view('admin.pages.index');
})->name('admin.index');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title', 'body', 'category_id', 'excerpt', 'slug'];


    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function visits()
    {
        return visits($this);
    }

    public function link($params = [])
    {
        return route('posts.show', array_merge([$this->id, $this->slug], $params));
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Handlers\ImageUploadHandler;
use App\Http\Requests\PostRequest;
use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PostsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * @param Post $post
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(Post $post)
    {
        $categories = Category::all();
        return view('posts.create_and_edit',compact('post','categories'));
    }

    /**
     * @param PostRequest $request
     * @param Post $post
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(PostRequest $request, Post $post)
    {
        $post->fill($request->all());
        $post->user_id = Auth::id();
        $post->save();
        return redirect()->to($post->link())->with('message', '发布成功');
    }

    /**
     * @param Request $request
     * @param Post $post
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector|\Illuminate\View\View
     */
    public function show(Request $request, Post $post)
    {
        if ( ! empty($post->slug) && $post->slug != $request->slug) {
            return redirect($post->link(), 301);
        }

        $post->visits()->increment();

        return view('posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $this->authorize('update', $post);
        $categories = Category::all();
        return view('posts.create_and_edit', compact('post', 'categories'));
    }

    /**
     * @param PostRequest $request
     * @param Post $post
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(PostRequest $request, Post $post)
    {
        $this->authorize('update', $post);
        $post->update($request->all());

        return redirect()->to($post->link())->with('success', '更新成功！');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function uploadImage(Request $request, ImageUploadHandler $uploader)
    {
        // 判断是否有上传文件，并赋值给 $file
        if ($file = $request->file('image')) {
            // 保存图片到本地
            $result = $uploader->save($request->image, 'posts', \Auth::id(), 1024);
            // 图片保存成功的话
            if ($result) {
                //$data['filename'] = $result['path'];
                return [
                    'filename' =>  $result['path']
                ];
            }
            else{
                return [
                    'error' => 'Error while uploading file'
                ];
            }
        }
    }
}

resources/views/posts/_reply_list.blade.php
<!--评论-->
<div class="">
    <div class="card">
        <div class="card-header" style="margin-bottom: 0.3rem; margin-top: 0.5rem">
            @if(count($replies) <= 0)
                暂无回复
            @else
                {{count($replies)}}个回复
            @endif

        </div>
        <div class="card-body">
            {{--<div>--}}
                {{--<p><i class="fa fa-bookmark fa-3x" style="color: #309C04;" aria-hidden="true"></i>--}}
                    {{--<span class="align-top">最佳回复</span>--}}
                {{--</p>--}}
                {{--<hr/>--}}
            {{--</div>--}}
            @foreach ($replies as $index => $reply)
                <div class="replay-item">
                    <em class="aw-border-radius-5 aw-vote-count pull-left disabled" style="background: #F2F2F2;
    color: #999; min-width: 25px; text-align: center; border-radius: 5px;">1</em>
                    <div class="mod-head">
                        <p>
                            <a class="aw-user-name" href="#" data-id="66994">
                                {{ $reply->user->name }} </a>
                            <i style="color: #a5d300;" class="fa fa-vimeo" aria-hidden="true">
                                {{ $reply->created_at->diffForHumans() }}
                            </i>
                            <a class="pull-right" href="#" data-id="66994">
                                <img class="aw-user-img"
                                     src="{{ $reply->user->avatar }}"
                                     alt="{{ $reply->user->name }}">
                            </a>
                        </p>
                    </div>
                    <div class="replay-content">
                        {!! convert_markdown_to_html($reply->content) !!}
                    </div>

                    <div class="mod-footer" style="font-size: 12px;">
                        <i class="fa fa-thumbs-o-up"></i>
                        <a class="aw-add-comment" style="margin-left: 5px;color: #999; "
                           href="javascript:;">
                            <i class="fa fa-reply" aria-hidden="true"></i>
                        </a>
                        <hr/>
                    </div>
                </div>
            @endforeach

        </div>
    </div>
</div>

resources/views/posts/categories.blade.php
<div class="card text-white bg-info mb-3" style="max-width: 25rem; margin-top: 1rem;">
    <div class="card-header">
        <span>
            标签云
        </span>
    </div>
    <div class="card-body">
        <div class="tags">
            @foreach(\App\Models\Category::all() as $category)
                <span style="background-color: {{ $category->color }}" class="badge">{{ $category->name }}</span>

            @endforeach
        </div>

    </div>
</div>

resources/views/posts/create_and_edit.blade.php
@extends('layouts.app')
@section('title', '新建文章')

@section('styles')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/highlight.js/latest/styles/github.min.css">
@stop

@section('content')
    {{--@include('users._user_profile')--}}
    <div class="container">
        {{--@include('layouts._left_users')--}}
        <div class=" ">

            <h2 class="text-center">
                <i class="glyphicon glyphicon-edit"></i>
                @if($post->id)
                    编辑文章
                @else
                    新建文章
                @endif
            </h2>

            <hr>

            {{--@include('common.error')--}}

            @if($post->id)
                <form action="{{ route('posts.update', $post->id) }}" method="POST" accept-charset="UTF-8">
                    <input type="hidden" name="_method" value="PUT">
                    @else
                        <form action="{{ route('posts.store') }}" method="POST" accept-charset="UTF-8">
                            @endif

                            <input type="hidden" name="_token" value="{{ csrf_token() }}">

                            <div class="form-group">
                                <input class="form-control" type="text" name="title"
                                       value="{{ old('title', $post->title ) }}" placeholder="请填写标题" required/>
                            </div>

                            <div class="form-group">
                                <select class="form-control" name="category_id" required>
                                    <option value="" hidden disabled {{ $post->id ? '' : 'selected' }}>请选择分类</option>
                                    @foreach ($categories as $value)
                                        <option value="{{ $value->id }}" {{ $post->category_id == $value->id ? 'selected' : '' }}>{{ $value->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <textarea name="body" class="form-control"
                                          id="simplemde">{{ old('body', $post->body ) }}</textarea>
                            </div>


                            <div class="well well-sm">
                                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"
                                                                                    aria-hidden="true"></span> 保存
                                </button>
                            </div>
                        </form>
        </div>
    </div>

@stop

@section('scripts')
    <script src="{{asset('js/inline-attachment.js')}}"></script>
    <script src="{{asset('js/codemirror.inline-attachment.js')}}"></script>

    {{--<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>--}}
    <script src="{{ asset('js/simplemde.min.js') }}"></script>
    {{--<script src="https://cdn.jsdelivr.net/highlight.js/latest/highlight.min.js"></script>--}}

    <script>

        $(document).ready(function () {
            var simplemde = new SimpleMDE({
                spellChecker: false,
                autosave: {
                    enabled: true,
                    delay: 5000,
                    unique_id: "topic_content"
                },
                forceSync: true,
                tabSize: 4,
                toolbar: [
                    "bold", "italic", "heading", "|", "quote", "code", "table",
                    "horizontal-rule", "unordered-list", "ordered-list", "|",
                    "link", "image", "|", "side-by-side", 'fullscreen', "|",
                    {
                        name: "guide",
                        action: function customFunction(editor) {
                            var win = window.open('https://github.com/riku/Markdown-Syntax-CN/blob/master/syntax.md', '_blank');
                            if (win) {
                                //Browser has allowed it to be opened
                                win.focus();
                            } else {
                                //Browser has blocked it
                                alert('Please allow popups for this website');
                            }
                        },
                        className: "fa fa-info-circle",
                        title: "Markdown 语法！",
                    },
                    {
                        name: "publish",
                        action: function customFunction(editor) {
                            $('#topic-submit').click();
                        },
                        className: "fa fa-paper-plane",
                        title: "发布文章",
                    }
                ],
            });

            inlineAttachment.editors.codemirror4.attach(simplemde.codemirror, {
                uploadUrl: '/upload_image',
                uploadFieldName: "image",
                //urlText: "\n ![file]({filename})\n\n",
                extraParams: {
                    '_token': '{{ csrf_token() }}',
                },
                onFileUploadResponse: function (xhr) {
                    var result = JSON.parse(xhr.responseText),
                        filename = result[this.settings.jsonFieldName];

                    if (result && filename) {
                        var newValue;
                        if (typeof this.settings.urlText === 'function') {
                            newValue = this.settings.urlText.call(this, filename, result);
                        } else {
                            newValue = this.settings.urlText.replace(this.filenameTag, filename);
                        }
                        var text = this.editor.getValue().replace(this.lastValue, newValue);
                        this.editor.setValue(text);
                        this.settings.onFileUploaded.call(this, filename);
                    }
                    return false;
                }
            });


            // http://pandoc.org/README.html#pandocs-markdown
            var pandoc = [{
                filter: 'h1',
                replacement: function (content, node) {
                    var underline = Array(content.length + 1).join('=');
                    return '\n\n' + content + '\n' + underline + '\n\n';
                }
            },

                {
                    filter: 'h2',
                    replacement: function (content, node) {
                        var underline = Array(content.length + 1).join('-');
                        return '\n\n' + content + '\n' + underline + '\n\n';
                    }
                },

                {
                    filter: 'sup',
                    replacement: function (content) {
                        return '^' + content + '^';
                    }
                },

                {
                    filter: 'sub',
                    replacement: function (content) {
                        return '~' + content + '~';
                    }
                },

                {
                    filter: 'br',
                    replacement: function () {
                        return '\\\n';
                    }
                },

                {
                    filter: 'hr',
                    replacement: function () {
                        return '\n\n* * * * *\n\n';
                    }
                },

                {
                    filter: ['em', 'i', 'cite', 'var'],
                    replacement: function (content) {
                        return '*' + content + '*';
                    }
                },

                {
                    filter: function (node) {
                        var hasSiblings = node.previousSibling || node.nextSibling;
                        var isCodeBlock = node.parentNode.nodeName === 'PRE' && !hasSiblings;
                        var isCodeElem = node.nodeName === 'CODE' ||
                            node.nodeName === 'KBD' ||
                            node.nodeName === 'SAMP' ||
                            node.nodeName === 'TT';

                        return isCodeElem && !isCodeBlock;
                    },
                    replacement: function (content) {
                        return '`' + content + '`';
                    }
                },

                {
                    filter: function (node) {
                        return node.nodeName === 'A' && node.getAttribute('href');
                    },
                    replacement: function (content, node) {
                        var url = node.getAttribute('href');
                        var titlePart = node.title ? ' "' + node.title + '"' : '';
                        if (content === url) {
                            return '<' + url + '>';
                        } else if (url === ('mailto:' + content)) {
                            return '<' + content + '>';
                        } else {
                            return '[' + content + '](' + url + titlePart + ')';
                        }
                    }
                },

                {
                    filter: 'li',
                    replacement: function (content, node) {
                        content = content.replace(/^\s+/, '').replace(/\n/gm, '\n    ');
                        var prefix = '-   ';
                        var parent = node.parentNode;

                        if (/ol/i.test(parent.nodeName)) {
                            var index = Array.prototype.indexOf.call(parent.children, node) + 1;
                            prefix = index + '. ';
                            while (prefix.length < 4) {
                                prefix += ' ';
                            }
                        }

                        return prefix + content;
                    }
                }
            ];

            // http://pandoc.org/README.html#smart-punctuation
            var escape = function (str) {
                return str.replace(/[\u2018\u2019\u00b4]/g, "'")
                    .replace(/[\u201c\u201d\u2033]/g, '"')
                    .replace(/[\u2212\u2022\u00b7\u25aa]/g, '-')
                    .replace(/[\u2013\u2015]/g, '--')
                    .replace(/\u2014/g, '---')
                    .replace(/\u2026/g, '...')
                    .replace(/[ ]+\n/g, '\n')
                    .replace(/\s*\\\n/g, '\\\n')
                    .replace(/\s*\\\n\s*\\\n/g, '\n\n')
                    .replace(/\s*\\\n\n/g, '\n\n')
                    .replace(/\n-\n/g, '\n')
                    .replace(/\n\n\s*\\\n/g, '\n\n')
                    .replace(/\n\n\n*/g, '\n\n')
                    .replace(/[ ]+$/gm, '')
                    .replace(/^\s+|[\s\\]+$/g, '');
            };

            var convert = function (str) {
                return escape(toMarkdown(str, {
                    converters: pandoc,
                    gfm: true
                }));
            };

            // var pastebin = document.querySelector('#pastebin');

            // document.addEventListener('keydown', function(event) {
            //     if (event.ctrlKey || event.metaKey) {
            //         if (String.fromCharCode(event.which).toLowerCase() === 'v') {
            //             pastebin.innerHTML = '';
            //             pastebin.focus();
            //         }
            //     }
            // });

            // pastebin.addEventListener('paste', function() {
            //     setTimeout(function() {
            //         var html = pastebin.innerHTML;
            //         var markdown = convert(html);

            //         simplemde.codemirror.getDoc().setValue(simplemde.codemirror.getDoc().getValue() +"\n"+markdown);

            //         simplemde.codemirror.focus();
            //     }, 200);
            // });


        });

    </script>

@stop

resources/views/posts/show.blade.php
@extends('layouts.app')
@section('title', "$post->title")
@section('description', "$post->title")
@section('keywords', "$post->title")

@section('styles')
    <link rel="stylesheet" href="{{ asset('css/jquery.atwho.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/atom-one-dark.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css">
@stop
@section('content')

    <div class="dg main">
        <div class="row">
            <div class="col-md-9 card">
                <div class="article border border-success">
                    <!--<h1 class="title">Hello World</h1>-->
                    <div class="alert alert-primary title text-center" role="alert">
                        {{$post->title}}
                    </div>
                    <div class="tag align-middle" style="text-align: center;	">
                        <div class="article-meta text-center">
                            <i class="fa fa-clock-o"></i> <abbr title="{{ $post->created_at }}"
                                                                class="timeago">{{$post->created_at->diffForHumans()}}</abbr>
                            <i class="fa fa-eye"></i> {{ $post->visits()->count() }}
                            <i class="fa fa-thumbs-o-up"></i> 19
                            <i class="fa fa-comments-o"></i> {{ $post->reply_count }}

                        </div>
                    </div>
                    <div class="replay-content" style="padding: 20px; padding-bottom: 20px;">
                        {!! convert_markdown_to_html($post->body) !!}

                        <div class="social-share"></div>
                    </div>

                    <div class="content-footer"
                         style="font-size: 12px; color: #999; padding-left: 20px; padding-bottom: 10px;">
                        <div class="aw-question-detail-meta">
                            <span class="aw-text-color-999">{{$post->created_at->diffForHumans()}}</span>
                            <a style="margin-right: 10px; color: rgb(153, 153, 153);" href="#replay">
                                <i class="fa fa-comment" style="margin-left: 10px; "></i>添加评论
                            </a>
                        </div>
                    </div>


                </div>

                @include('posts._reply_list',['replies' => $post->replies()->with('user')->get()])

                <!--评论回复框-->
                <div class="border-success" id="replay" style="margin-top: 1rem;">
                    <div class="alert alert-warning" role="alert">
                        支持 Markdown 格式, **粗体**、~~删除线~~、`单行代码`, 更多语法请见这里 <a class="alert-link"
                                                                           href="https://github.com/riku/Markdown-Syntax-CN/blob/master/syntax.md">Markdown</a>
                        语法
                    </div>

                    <div class="alert alert-info" role="alert">
                        <i class="fa fa-info" aria-hidden="true"></i>
                        请勿发布不友善或者负能量的内容。与人为善，比聪明更重要！
                    </div>
                    <form method="POST" action="{{ route('replies.store') }}"  accept-charset="UTF-8"
                          id="tweet-create-form" class="tweet-form reply-form">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <input type="hidden" name="post_id" value="{{ $post->id }}">
                        <div class="form-group emoji-picker-container">
                        <textarea class="form-control" rows="4" placeholder="认真评论；支持 Markdown 格式"
                                  name="content" id="reply_content"></textarea>
                            <div class="form-group reply-post-submit replay-data">
                                <div class="pull-left meta">
                                    <a href="javascript:;" class="action popover-with-html"
                                       data-content="黏贴或拖拽图片至输入<br>框内皆可上传图片" data-original-title="" title="">
                                        <i class="fa fa-picture-o"></i>
                                    </a>
                                    <a href="javascript:;" class="action popover-with-html"
                                       data-content="支持除了 H1~H6 以外的<br>GitHub 兼容 Markdown" data-original-title=""
                                       title="">
                                        支持 MD
                                    </a>
                                </div>
                                <div class="pull-right">
                            <span class="help-inline meta" title="Or Command + Enter" style="margin-right:10px"><span
                                        id="word-count">0</span> / 180</span>
                                    <button class="btn btn-outline-success btn-sm " type="submit">
                                        <i class="fa fa-send"></i> 回复
                                    </button>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div>

            @include('layouts.right',['posts' => visits(\App\Models\Post::class)->top(5)])

        </div>

        <i class="to-top fa fa-rocket fa-4x"></i>
    </div>

@stop

@section('scripts')
    {{--<script src="http://code.jquery.com/jquery.js"></script>--}}
    <script type="text/javascript"  src="{{ asset('js/jquery-1.11.0.min.js') }}"></script>


    <script type="text/javascript"  src="{{ asset('js/jquery.caret.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/jquery.atwho.min.js') }}"></script>

    <script type="text/javascript"  src="{{ asset('js/jquery.toTop.min.js') }}"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/js/jquery.share.min.js"></script>

    <script>
        $('#reply_content').atwho({
            at: "@",
            callbacks: {
                remoteFilter: function(query, callback) {
                    $.getJSON("/users_json", {q: query}, function(data) {
                        callback(data)
                    });
                }
            }
        })
    </script>

    <script>
        $('pre code').each(function (i, block) {
            hljs.highlightBlock(block);
        });
    </script>

    <script>
        $('.to-top').toTop({
            //options with default values
            autohide: true,  //boolean 'true' or 'false'
            offset: 420,     //numeric value (as pixels) for scrolling length from top to hide automatically
            speed: 500,      //numeric value (as mili-seconds) for duration
            right: 15,       //numeric value (as pixels) for position from right
            bottom: 30       //numeric value (as pixels) for position from bottom
        });
    </script>


@stop