routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@root')->name('root');

Route::get('/reprinted', function () {
    return view('reprinted');
});

Route::get('/sites','LinkController@index')->name('links.index');
Route::get('/links/create','LinkController@create')->name('links.create');
Route::post('/links/store','LinkController@store')->name('links.store');

Route::get('users_json','UsersController@usersJson')->name('users.json');


Auth::routes();

Route::group(['middleware' => 'auth'], function() {
    Route::get('/email_verify_notice', 'HomeController@emailVerifyNotice')
        ->name('email_verify_notice');

    Route::get('/email_verification/send', 'EmailVerificationController@send')->name('email_verification.send');
    Route::get('/email_verification/verify', 'EmailVerificationController@verify')->name('email_verification.verify');
    Route::get('/about','HomeController@about')->name('about');

    Route::resource('notifications', 'NotificationsController', ['only' => ['index']]);

    Route::group(['middleware' => 'email_verified'], function() {
        Route::resource('users','UsersController');
        Route::any('users/upload','UsersController@upload')->name('users.upload');

        Route::resource('posts','PostsController',['only' => ['index', 'create', 'store', 'update', 'edit', 'destroy']]);
        Route::post('upload_image', 'PostsController@uploadImage')->name('posts.upload_image');
        Route::resource('replies', 'RepliesController', ['only' => ['store', 'destroy']]);
        Route::get('users/{user}/follow', 'UsersController@follow')->name('users.follow');
        Route::get('users/{user}/unfollow', 'UsersController@unfollow')->name('users.unfollow');

        Route::post('tweets','TweetsController@store')->name('tweets.store');

    });

});
Route::resource('tweets','TweetsController',['only' => ['index','show']]);

Route::get('posts/{post}/{slug?}', 'PostsController@show')->name('posts.show');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/oauth/github', 'AuthController@redirectToProvider')->name('oauth.github');
Route::get('/oauth/github/callback', 'AuthController@handleProviderCallback')->name('oauth.github.callback');

Route::get('/oauth/qq', 'AuthController@qqRedirectToProvider')->name('oauth.qq');
Route::get('/oauth/qq/callback', 'AuthController@qqHandleProviderCallback')->name('oauth.qq.callback');

Route::get('oauth/perfect', 'AuthController@perfect')->name('oauth.perfect');
Route::post('oauth/perfect/store','AuthController@store')->name('auth.perfect.store');



//后台相关
Route::get('/admin/login','Admin\Auth\LoginController@showLoginForm');
Route::post('/admin/login','Admin\Auth\LoginController@login')->name('admin.login');
Route::post('/admin/logout','Admin\Auth\LoginController@logout')->name('admin.logout');

Route::get('/admin/index',function (){
    return view('admin.pages.index');
})->name('admin.index');

resources/views/layouts/_footer.blade.php
<footer id="footer" class="footer">
        <div class="alert alert-dark alert-footer " role="alert">
            <p class="mb-0 text-center">
                &copy; Company 2018-<a href="{{ url('/') }}">贺德强</a> 版权所有
                <span style="color: #e27575;font-size: 14px;"></span>
                <a class="alert-link" href="http://www.miitbeian.gov.cn">冀ICP备17012521号-2
                </a>

            <span class="mb-0 pull-right">
                <a class="footer-contact" href="{{ url('/sites#web') }}">推荐资源</a>
                <a class="footer-contact" href="{{ url('/sites#blog') }}">友情链接</a>
                来自: {{$location}}</span>
            </p>
        </div>
</footer>

resources/views/layouts/_header.blade.php
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url('/') }}">LaravelCode</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url('/') }}">原创 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url('/reprinted') }}">转载</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">分类</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('tweets.index') }}">动弹</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://flarum.laravelcode.cn">后宫</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url('about') }}">关于我</a>
                </li>
                {{--<li class="nav-item dropdown">--}}
                {{--<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">--}}
                {{--Dropdown--}}
                {{--</a>--}}
                {{--<div class="dropdown-menu" aria-labelledby="navbarDropdown">--}}
                {{--<a class="dropdown-item" href="#">Action</a>--}}
                {{--<a class="dropdown-item" href="#">Another action</a>--}}
                {{--<div class="dropdown-divider"></div>--}}
                {{--<a class="dropdown-item" href="#">Something else here</a>--}}
                {{--</div>--}}
                {{--</li>--}}
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            {{--<a class="btn btn-outline-success mr-sm-2 my-2 my-sm-1" href="{{ url('login') }}" role="button">登录</a>--}}
            {{--<a class="btn btn-outline-success my-2 my-sm-0" href="{{ url('register') }}" role="button">注册</a>--}}
            <!-- 登录注册链接开始 -->
            </form>
            @guest
                <a class="btn btn-outline-success mr-sm-2 my-2 my-sm-1"
                                        href="{{ route('login') }}">登录</a>
                <a class="btn btn-outline-success mr-sm-2 my-2 my-sm-1"
                                        href="{{ route('register') }}">注册</a>
            @else
                <li>
                    <a href="{{ route('notifications.index') }}" class="fa fa-bell" style="margin-left: 0.7rem; margin-right: 1rem; color: {{ Auth::user()->notification_count > 0 ? 'red' : '#2ab27b' }} ;">
                            {{--<span class="badge badge-{{ Auth::user()->notification_count > 0 ? 'hint' : 'fade' }} " style=" display: inline-flex" title="消息提醒">--}}
                                {{--{{ Auth::user()->notification_count }}--}}
                            {{--</span>--}}
                    </a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="user-avatar pull-left" style="margin-right:8px; margin-top:-5px;">
                                <img src="{{ Auth::user()->avatar }}"
                                     class="img-responsive rounded-circle" width="30px" height="30px">
                            </span>
                        {{ Auth::user()->name }} <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li>
                            <a class="dropdown-item" href="{{ url('/users').'/'. Auth::id() }}">个人资料</a>
                        </li>
                        <li class="dropdown-item">
                            <a href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                退出登录
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    </ul>
                </li>
            @endguest
        <!-- 登录注册链接结束 -->

        </div>
    </nav>
</div>

resources/views/layouts/_left_users.blade.php
<div class="row user">
    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <a class="nav-link active " id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">文章</a>
        <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">话题</a>
        <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">回复</a>
        <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">动弹</a>
    </div>
    <div class="tab-content" id="v-pills-tabContent">
        @yield('user_content')
    </div>
</div>

resources/views/layouts/_message.blade.php
@if (Session::has('message'))
    <div class="alert alert-info user-edit-container">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        {{ Session::get('message') }}
    </div>
@endif

@if (Session::has('success'))
    <div class="alert alert-success user-edit-container">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        {{ Session::get('success') }}
    </div>
@endif

@if (Session::has('danger'))
    <div class="alert alert-danger user-edit-container">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        {{ Session::get('danger') }}
    </div>
@endif


@if (Session::has('error'))
    <div class="alert alert-danger user-edit-container">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        {{ Session::get('error') }}
    </div>
@endif

resources/views/layouts/_right-reprinted.blade.php
<div class="col-md-3">
    <div class="card text-white bg-dark mb-3" style="max-width: 25rem; opacity: 0.8;">
        <div class="card-header">版权申明</div>
        <div class="card-body">

            <p class="card-text saying">
                本页内容均来自互联网优质内容，<strong class="font-weight-bold">版权并非本网站；</strong>
            </p>
            <p class="card-text saying">
                我们在原著允许转载的情况下进行转载。并且附上原著网站地址，文章链接等；
            </p>
            <p class="card-text saying">
                如果您觉得此举不妥，请告知我，我会第一时间进行下线处理；
            </p>
        </div>
    </div>


    <div class="list-group" style="max-width: 25rem;">
        <a href="#" class="list-group-item list-group-item-action active">
            热门排行
        </a>
        <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in</a>
        <a href="#" class="list-group-item list-group-item-action">Morbi leo risus</a>
        <a href="#" class="list-group-item list-group-item-action">Porta ac consectetur ac</a>
        <a href="#" class="list-group-item list-group-item-action disabled">Vestibulum at eros</a>
    </div>

    @include('posts.categories')
</div>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="baidu_union_verify" content="7f5898b5ac3330adbd6787663d8128dc">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    {{--<title>{{ config('app.name', 'LaravelCode') }}</title>--}}
    <title>@yield('title')</title>
    <meta name="description" content="@yield('description')">
    <meta name="keywords" content="@yield('keywords')">
    <!-- Styles -->
    <link rel="shortcut icon" href="{{ asset('32x32.ico') }}" >
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('styles')
</head>
<body>
<div id="app">
    <div id="container">
        @include('layouts._header')
        <div class="container main-container">

            @yield('content')


        </div>
        @include('layouts._footer')
    </div>

</div>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
@yield('scripts')
</body>
</html>

resources/views/layouts/right.blade.php
<div class="col-md-3">
                <div class="card text-white bg-success mb-3" style="max-width: 25rem; opacity: 0.8;">
                    <div class="card-header">网站公告</div>
                    <div class="card-body">

                        <p class="card-text saying">
                            LaravelCode 正式上线啦！
                        </p>
                    </div>
                </div>


                <div class="list-group" style="max-width: 25rem;">
                    <a href="#" class="list-group-item list-group-item-action active">
                        热门排行
                    </a>

                   @foreach($posts as $post)
                        <a href="{{ $post->link() }}" class="list-group-item list-group-item-action">{{ $post->title }}</a>

                    @endforeach

                </div>



                @include('posts.categories')
            </div>